"""empty message

Revision ID: 190c607831bc
Revises: 2810b6a6f6e5
Create Date: 2015-08-05 17:57:02.770000

"""

# revision identifiers, used by Alembic.
revision = '190c607831bc'
down_revision = '2810b6a6f6e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('web_link', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'web_link')
    ### end Alembic commands ###
