"""empty message

Revision ID: 2810b6a6f6e5
Revises: 40b1b83135bf
Create Date: 2015-07-25 22:59:44.041000

"""

# revision identifiers, used by Alembic.
revision = '2810b6a6f6e5'
down_revision = '40b1b83135bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
