"""empty message

Revision ID: 2c9540f5e7f3
Revises: 190c607831bc
Create Date: 2015-08-19 12:58:51.893000

"""

# revision identifiers, used by Alembic.
revision = '2c9540f5e7f3'
down_revision = '190c607831bc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rating', 'score',
               existing_type=mysql.FLOAT(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rating', 'score',
               existing_type=mysql.FLOAT(),
               nullable=True)
    ### end Alembic commands ###
