"""empty message

Revision ID: 2f95b5284a7b
Revises: None
Create Date: 2015-07-25 21:11:01.655000

"""

# revision identifiers, used by Alembic.
revision = '2f95b5284a7b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
