"""empty message

Revision ID: 40b1b83135bf
Revises: 2f95b5284a7b
Create Date: 2015-07-25 22:01:19.956000

"""

# revision identifiers, used by Alembic.
revision = '40b1b83135bf'
down_revision = '2f95b5284a7b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
