"""empty message

Revision ID: 42cffcdb86cb
Revises: 5ac572c0323d
Create Date: 2015-08-19 13:46:55.840000

"""

# revision identifiers, used by Alembic.
revision = '42cffcdb86cb'
down_revision = '5ac572c0323d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
