"""empty message

Revision ID: 4842f85aa3dd
Revises: 2c9540f5e7f3
Create Date: 2015-08-19 12:59:03.833000

"""

# revision identifiers, used by Alembic.
revision = '4842f85aa3dd'
down_revision = '2c9540f5e7f3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
