"""empty message

Revision ID: 5ac572c0323d
Revises: 4842f85aa3dd
Create Date: 2015-08-19 13:27:06.659000

"""

# revision identifiers, used by Alembic.
revision = '5ac572c0323d'
down_revision = '4842f85aa3dd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=128), nullable=False))
    op.add_column('user', sa.Column('username', sa.String(length=128), nullable=False))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_index('ix_user_nickname', table_name='user')
    op.drop_column('user', 'nickname')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nickname', mysql.VARCHAR(length=128), nullable=False))
    op.create_index('ix_user_nickname', 'user', ['nickname'], unique=True)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'username')
    op.drop_column('user', 'password')
    ### end Alembic commands ###
